### PR TITLE
Update librosa requirement section 

### PR DESCRIPTION
**Pull request by KahLiang**
According to the librosa change log for .7.0 >> (Root mean square error (rmse) has been renamed to rms)

### CODE REVIEW

**Comment by Demfier** [comment]
Hi @KahLiang,

Thanks for the PR! Could you also update the README to reflect on this librosa change? Also, if you could confirm that you have a valid output after this change, that'd be great.

Thanks,
Gaurav.

**Comment by KahLiang** [comment]
Yes, it can run smoothly and generate the "audio_features.csv" after changing it.  I test the code with the latest version of the IEMOCAP dataset.

**Comment by Demfier** [comment]
Hi @KahLiang,

I meant updating the [Requirements](https://github.com/Demfier/multimodal-speech-emotion-recognition#requirements) section, which currently says `librosa==0.6.3` to `librosa==0.7.0`. You don't need to make any changes to the [instructions](https://github.com/Demfier/multimodal-speech-emotion-recognition#instructions-to-run-the-code). Also, it'd be great if you could do the change in this PR and close #29.

Thanks a bunch!
Gaurav.

**Comment by KahLiang** [comment]
Hi @Demfier,

I updated the Requirements section and closed PR #29. Thank you.

**Review by Demfier — APPROVED** [review]

**Pull request merged**
